# Generated by Django 6.0.4 on 2026-04-27 02:28

import contracts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado'), ('suspenso', 'Suspenso'), ('encerrado', 'Encerrado')], default='ativo', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='clients.cliente')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='companies.empresa')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ContratoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=80)),
                ('dados', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='contracts.contrato')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_contrato', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historico do contrato',
                'verbose_name_plural': 'Historicos dos contratos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ContratoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=contracts.models.caminho_arquivo_contrato)),
                ('versao', models.PositiveIntegerField(editable=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='contracts.contrato')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arquivos_contrato_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arquivo do contrato',
                'verbose_name_plural': 'Arquivos dos contratos',
                'ordering': ['-versao'],
                'constraints': [models.UniqueConstraint(fields=('contrato', 'versao'), name='contrato_arquivo_versao_unica')],
            },
        ),
    ]
